version: 0.2
###
# This build project is for the build frontend in the rasd-service pipeline

env:
  shell: bash
  variables:
    LAMBDA_NAME: rasd_fastapi

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - cd backend || exit 2
      - apt update && apt install pipx -y
      # - apt-get update && apt-get install curl -y
      - pipx ensurepath
      - pipx install poetry==1.3.2
      - export POETRY_HOME=/root/.local

  pre_build:
    commands:
      - pwd
      - ls -al

  build:
    commands:
      - $POETRY_HOME/bin/poetry export -f requirements.txt --with $LAMBDA_NAME -o lambdas/$LAMBDA_NAME/requirements.txt
      - mkdir -p dist/$LAMBDA_NAME
      - pip install -r lambdas/$LAMBDA_NAME/requirements.txt --target ./dist/$LAMBDA_NAME --upgrade

  post_build:
    commands:
      - cp -r lambdas/$LAMBDA_NAME dist/$LAMBDA_NAME/

artifacts:
  files:
    - backend/dist/rasd_fastapi/**/*
  name: BuildBackendArtifact
  discard-paths: no
