version: 0.2
###
# Deletes all objects from the rasd service bucket, this needs to be done 
# before the teardown action so the bucket can be removed

env:
  shell: bash

phases:
  build:
    commands:
      - echo emptying bucket $BACKUP_BUCKET
      - aws s3 rm s3://$BACKUP_BUCKET --recursive
