version: 0.2
###
# This build project is for the lint and build frontend in the rasd-service pipeline

env:
  shell: bash
  variables:
    BUCKET_NAME: $STATIC_BUCKET

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - npm install

  pre_build:
    commands:
      - npm run lint
      - npm run prettier-check

  build:
    commands:
      - pwd
      - npm run build -- --mode production #  -- --mode $CI_COMMIT_BRANCH
  post_build:
    commands:
      - echo "Uploading files to S3 bucket ${BUCKET_NAME}..."
      - aws s3 sync dist s3://${BUCKET_NAME} --delete

artifacts:
  files:
    - frontend/dist/**/*
  name: BuildFrontendArtifact
  discard-paths: no
