version: 0.2
###
# This build project is for the build frontend in the rasd-service pipeline

env:
  shell: bash
  variables:
    LAMBDA_NAME: rasd_fastapi

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - cd backend || exit 2
      - apt update && apt install pipx -y
      # - apt-get update && apt-get install curl -y
      - pipx ensurepath
      - pipx install poetry==1.3.2
      - pipx install poethepoet
      - export POETRY_HOME=/root/.local
      - $POETRY_HOME/bin/poetry install

  build:
    commands:
      - poe test
