version: 0.2
###
# This build project is for the build frontend in the rasd-service pipeline

env:
  shell: bash
  variables:
    LAMBDA_NAME: rasd_fastapi

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - cd backend || exit 2
      - apt update && apt install pipx -y
      # - apt-get update && apt-get install curl -y
      - pipx ensurepath
      - pipx install poetry==2.1.4
      - pipx install poethepoet
      - export POETRY_HOME=/root/.local
      - $POETRY_HOME/bin/poetry self add poetry-plugin-export
      - $POETRY_HOME/bin/poetry install

  pre_build:
    commands:
      - export AWS_COGNITO_CLIENT_SECRET_KEY=$(aws cognito-idp describe-user-pool-client --user-pool-id $AWS_COGNITO_POOL_ID --client-id $AWS_COGNITO_CLIENT_ID --query "UserPoolClient.ClientSecret" --output text)

  build:
    commands:
      - export PATH="$PATH:/root/.local/bin"
      - poe test
