AWSTemplateFormatVersion: '2010-09-09'
Description: The RASD service stack

Parameters:
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to

Conditions:
  IsDev: !Equals
    - !Ref pEnvironment
    - development
  NotDev: !Not
    - !Condition IsDev

Resources:
  DynamoDBTableDataAccessRequests:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeType: S
          AttributeName: id
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - KeyType: HASH
          AttributeName: id

  DynamoDBTableMetadata:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeType: S
          AttributeName: id
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - KeyType: HASH
          AttributeName: id

  DynamoDBTableOrganisations:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeType: S
          AttributeName: id
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - KeyType: HASH
          AttributeName: id

  DynamoDBTableRegistrations:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeType: S
          AttributeName: id
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - KeyType: HASH
          AttributeName: id

  CognitoPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 3
      Schema:
        - AttributeDataType: String
          Mutable: true
          Name: organisation_id
        - AttributeDataType: String
          Mutable: true
          Name: family_name
          Required: true
          StringAttributeConstraints:
            MaxLength: '2048'
            MinLength: '0'
        - AttributeDataType: String
          Mutable: true
          Name: given_name
          Required: true
          StringAttributeConstraints:
            MaxLength: '2048'
            MinLength: '0'
        - AttributeDataType: String
          Mutable: true
          Name: email
          Required: true
          StringAttributeConstraints:
            MaxLength: '2048'
            MinLength: '0'

  CognitoGroupAdmin:
    Type: AWS::Cognito::UserPoolGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      GroupName: Administrators
      Precedence: 1
      UserPoolId: ap-southeast-2_H0QBU7BxJ

  CognitoGroupCustodians:
    Type: AWS::Cognito::UserPoolGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      GroupName: DataCustodians
      Precedence: 2
      UserPoolId: ap-southeast-2_H0QBU7BxJ

  CognitoGroupRequestors:
    Type: AWS::Cognito::UserPoolGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      GroupName: DataRequestors
      Precedence: 3
      UserPoolId: ap-southeast-2_H0QBU7BxJ

  CognitoAppClientRasdbackend:
    Type: AWS::Cognito::UserPoolClient
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolId: ap-southeast-2_H0QBU7BxJ
      PreventUserExistenceErrors: ENABLED
      GenerateSecret: True
      EnableTokenRevocation: True
      AccessTokenValidity: 180
      IdTokenValidity: 180
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
      ReadAttributes:
        - given_name
        - email_verified
        - custom:organisation_id
        - zoneinfo
        - website
        - preferred_username
        - name
        - locale
        - phone_number
        - family_name
        - birthdate
        - middle_name
        - phone_number_verified
        - profile
        - picture
        - address
        - gender
        - updated_at
        - nickname
        - email
      WriteAttributes:
        - given_name
        - custom:organisation_id
        - zoneinfo
        - website
        - preferred_username
        - name
        - locale
        - phone_number
        - family_name
        - birthdate
        - middle_name
        - profile
        - picture
        - address
        - gender
        - updated_at
        - nickname
        - email

  ApiGatewayCustomDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    DeletionPolicy: Delete
    Properties:
      DomainName: service.rasd.org.au
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2

  SESDomainIdentity:
    Type: AWS::SES::EmailIdentity
    DeletionPolicy: Delete
    Properties:
      DkimAttributes:
        SigningEnabled: true
      DkimSigningAttributes:
        NextSigningKeyLength: RSA_2048_BIT
      EmailIdentity: service.rasd.org.au
      MailFromAttributes:
        MailFromDomain: mail.service.rasd.org.au
